### ISSUE TITLE
Moving to absolute import from relative import

### ISSUE THREAD

**Issue by alhaqhassan** [upcjmi/upcjmi-react-app#14]
We are using relative imports in all our files. ex: `../../components/signUp/signInCard` but this creates a lot of confusion. Change all relative import to absolute imports ex: `components/signUp/signInCard`.

HELP:
create a file `jsconfig.json` and add following things:
```json
{
  "compilerOptions": {
    "baseUrl": "src/"
  }
}
```
Also configure _eslint_ by adding following to settings of file .`.eslint`
```json
"settings": {
    "import/resolver": {
      "node": {
        "paths": ["src"]
      }
    }
  }
```

Now all imports will work with both absolute and relative imports. Change all relative imports to absolute imports excepts those of which lies in same folder.

Requirement to merge pull request:
Change **ALL** the import styles.

**Comment by bpallares** [comment]
Can I take a look at this?

**Comment by bpallares** [comment]
oh, this has been solved already on https://github.com/upcjmi/upcjmi-react-app/pull/18

**Comment by Faisal-Manzer** [comment]
Cheers to @ashertoufeeq for solving that.
