### ISSUE TITLE
Show add to home screen modal instead of mini-info bar

### ISSUE THREAD

**Issue by nashrahnaseem** [upcjmi/upcjmi-react-app#22]
**Is your feature request related to a problem? Please describe.**
the mini-info bar goes unnoticed when browsing the web app.

**Describe the solution you'd like**
Instead, it should have an eye-catching modal to notify the user that this is a PWA.

**Comment by nashrahnaseem** [comment]
I would like to help. 
I saw this article https://developers.google.com/web/fundamentals/app-install-banners

**Comment by Faisal-Manzer** [comment]
We would love your contribution ❤️
I am assigning this to you.

Also, can you clear me about the prompt on safari?
