### ISSUE TITLE
Add OneSignal Push Notification.

### ISSUE THREAD

**Issue by nashrahnaseem** [upcjmi/upcjmi-react-app#24]
As we have a PWA can we add web push notification?

https://app.leanboard.io/board/ea8acc9b-a831-43c4-917a-37dc0e9e39a6

**Comment by Faisal-Manzer** [comment]
Yep, we will like to add that.
Use OneSignal SDK to add push notification.

**Comment by alhaqhassan** [comment]
I am doing that.

**Comment by Faisal-Manzer** [comment]
Push notification is enabled but we want to show popup programmatically. Just like e2296473e3f0a9c839a4ed2d71ff834d5adde145

**Comment by ashertoufeeq** [comment]
Can I work on it?

**Comment by Faisal-Manzer** [comment]
@ashertoufeeq we will love your contribution ❤️
