### ISSUE TITLE
Correction in implementation of #22

### ISSUE THREAD

**Issue by 1arshan** [upcjmi/upcjmi-react-app#27]
**Describe the bug**
- When A2HS modal comes it is non-closable that is bad for UX
- Modal on a large screen is not good in UI
- No installing feedback

**To Reproduce**

1. Open the website
2. Clear all data and unregister
3. Wait for 30sec
4. See the banner

**Comment by 1arshan** [comment]
Can I take this?

**Comment by Faisal-Manzer** [comment]
Yep for sure. We would love your contribution ❤️

**Comment by 1arshan** [comment]
@Faisal-Manzer Can you add hacktober label in this issue?

**Comment by Faisal-Manzer** [comment]
It's if no need but yeah. I am adding.

**Comment by Faisal-Manzer** [comment]
@1arshan I added hacktober label and assigned you. Waiting for your PR.

**Comment by Faisal-Manzer** [comment]
Thanks, @1arshan 
But I am also concerned about the safari. Any tips on that?
